import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Supabase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` m-0 box-border p-0 ${inter.className} bg-[#F4F5FA]`}>
        <header className=" text-white h-20 w-full bg-[#12bca2]  flex flex-col items-center">
          <h1 className="font-semibold uppercase mt-2">Supa Smoothies</h1>
          <nav className="mt-2">
            <Link href={"/"} className="mr-8 ">
              Home
            </Link>
            <Link href={"/create"}>Create new smoothie</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
